/* Generated By:JavaCC: Do not edit this line. CompilatudoConstants.java */
package CCompiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilatudoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int RETURN = 10;
  /** RegularExpression Id. */
  int MAIN = 11;
  /** RegularExpression Id. */
  int INCLUDE = 12;
  /** RegularExpression Id. */
  int DEFINE = 13;
  /** RegularExpression Id. */
  int WHILE = 14;
  /** RegularExpression Id. */
  int VOID = 15;
  /** RegularExpression Id. */
  int CHAR = 16;
  /** RegularExpression Id. */
  int FOR = 17;
  /** RegularExpression Id. */
  int DOUBLE = 18;
  /** RegularExpression Id. */
  int ASSIGN = 19;
  /** RegularExpression Id. */
  int GT = 20;
  /** RegularExpression Id. */
  int LT = 21;
  /** RegularExpression Id. */
  int EQ = 22;
  /** RegularExpression Id. */
  int LE = 23;
  /** RegularExpression Id. */
  int GE = 24;
  /** RegularExpression Id. */
  int NE = 25;
  /** RegularExpression Id. */
  int PLUS = 26;
  /** RegularExpression Id. */
  int PLUS_EQ = 27;
  /** RegularExpression Id. */
  int MINUS = 28;
  /** RegularExpression Id. */
  int MINUS_EQ = 29;
  /** RegularExpression Id. */
  int MULTIPLY = 30;
  /** RegularExpression Id. */
  int MULTIPLY_EQ = 31;
  /** RegularExpression Id. */
  int DIVIDE = 32;
  /** RegularExpression Id. */
  int DIVIDE_EQ = 33;
  /** RegularExpression Id. */
  int MOD = 34;
  /** RegularExpression Id. */
  int MOD_EQ = 35;
  /** RegularExpression Id. */
  int ADRESS = 36;
  /** RegularExpression Id. */
  int LEFT_SHIFT = 37;
  /** RegularExpression Id. */
  int RIGHT_SHIFT = 38;
  /** RegularExpression Id. */
  int INC = 39;
  /** RegularExpression Id. */
  int DEC = 40;
  /** RegularExpression Id. */
  int AND = 41;
  /** RegularExpression Id. */
  int OR = 42;
  /** RegularExpression Id. */
  int LPAREN = 43;
  /** RegularExpression Id. */
  int RPAREN = 44;
  /** RegularExpression Id. */
  int LBRACE = 45;
  /** RegularExpression Id. */
  int RBRACE = 46;
  /** RegularExpression Id. */
  int LBRACKET = 47;
  /** RegularExpression Id. */
  int RBRACKET = 48;
  /** RegularExpression Id. */
  int SEMICOLON = 49;
  /** RegularExpression Id. */
  int COMMA = 50;
  /** RegularExpression Id. */
  int DOT = 51;
  /** RegularExpression Id. */
  int HASHTAG = 52;
  /** RegularExpression Id. */
  int int_constant = 53;
  /** RegularExpression Id. */
  int float_constant = 54;
  /** RegularExpression Id. */
  int null_constant = 55;
  /** RegularExpression Id. */
  int char_constant = 56;
  /** RegularExpression Id. */
  int string_constant = 57;
  /** RegularExpression Id. */
  int ID = 58;
  /** RegularExpression Id. */
  int LETTER = 59;
  /** RegularExpression Id. */
  int DIGIT = 60;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 67;
  /** RegularExpression Id. */
  int INVALID_CONST = 68;
  /** RegularExpression Id. */
  int INVALID_IDCONST = 69;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multicomentario = 1;
  /** Lexical state. */
  int unicomentario = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"int\"",
    "\"if\"",
    "\"float\"",
    "\"else\"",
    "\"return\"",
    "\"main\"",
    "\"include\"",
    "\"define\"",
    "\"while\"",
    "\"void\"",
    "\"char\"",
    "\"for\"",
    "\"double\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"+=\"",
    "\"-\"",
    "\"-=\"",
    "\"*\"",
    "\"*=\"",
    "\"/\"",
    "\"/=\"",
    "\"%\"",
    "\"%=\"",
    "\"&\"",
    "\">>\"",
    "\"<<\"",
    "<INC>",
    "<DEC>",
    "\"&&\"",
    "\"||\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"#\"",
    "<int_constant>",
    "<float_constant>",
    "\"NULL\"",
    "<char_constant>",
    "<string_constant>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 63>",
    "\"//\"",
    "<token of kind 65>",
    "<token of kind 66>",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
    "<INVALID_IDCONST>",
    "\"\\\"\"",
  };

}
